var data={
    ccStone:{
        name:"光栅石",
        type:"s",
        level:-1
    },
    csStone:{
        name:"分形硅石",
        type:"s",
        level:-1,
    },
    dStone:{
        name:"金伯利亚石",
        type:"s",
        level:-1,
    },
    cice:{
        name:"可燃冰",
        type:"s",
        level:-1,
    },
    cStone:{
        name:"刺笋结晶",
        type:"s",
        level:-1,
    },
    pcStone:{
        name:"单极磁石",
        type:"s",
        level:-1,
    },
    CuM:{
        name:"铜矿",
        type:"s",
        level:0
    },
    FeM:{
        name:"铁矿",
        type:"s",
        level:0
    },
    CaM:{
        name:"石矿",
        type:"s",
        level:0
    },
    coalM:{
        name:"煤矿",
        type:"s",
        level:0
    },
    SiM:{
        name:"硅石",
        type:"s",
        level:0
    },
    TiM:{
        name:"钛石",
        type:"s",
        level:0
    },
    water:{
        name:"水",
        type:"l",
        level:0
    },
    oil:{
        name:"原油",
        type:"l",
        level:0
    },
    Cu:{
        name:"铜块",
        level:1,
        make:{
            item:[{
                id:"CuM",
                count:1
            }],
            time:1,
            count:1
        }
    },
    Fe:{
        name:"铁块",
        level:1,
        make:{
            item:[{
                id:"FeM",
                count:1
            }],
            time:1,
            count:1
        }
    },
    magnet:{
        name:"磁铁",
        level:1,
        make:{
            item:[{
                id:"FeM",
                count:1
            }],
            time:1.5,
            count:1
        }
    },
    stone:{
        name:"石材",
        level:1,
        make:{
            item:[{
                id:"CaM",
                count:1
            }],
            time:1,
            count:1
        }
    },
    glass:{
        name:"玻璃",
        level:1,
        make:{
            item:[{
                id:"CaM",
                count:2
            }],
            time:2,
            count:1
        }

    },
    eg:{
        name:"高能石墨",
        level:1,
        make:{
            item:[{
                id:"coalM",
                count:2
            }],
            time:2,
            count:1
        }
    },
    Si:{
        name:"高纯硅块",
        level:1,
        make:{
            item:[{
                id:"SiM",
                count:2
            }],
            time:2,
            count:1
        }
    },
    Ti:{
        name:"钛块",
        level:1,
        make:{
            item:[{
                id:"TiM",
                count:2
            }],
            time:2,
            count:1
        }
    },
    coil:{
        name:"磁线圈",
        level:2,
        make:{
            item:[{
                id:"magnet",
                count:2
            },{
                id:"Cu",
                count:1
            }],
            time:1,
            count:2
        }
    },
    steal:{
        name:"钢材",
        level:2,
        make:{
            item:[{
                id:"Fe",
                count:3
            }],
            time:3,
            count:1
        }
    },
    gear:{
        name:"齿轮",
        level:2,
        make:{
            item:[{
                id:"Fe",
                count:1
            }],
            time:1,
            count:1
        }
    },
    em:{
        name:"电机",
        level:3,
        make:{
            item:[{
                id:"Fe",
                count:2
            },{
                id:"magnet",
                count:1
            },{
                id:"gear",
                count:1
            }],
            time:2,
            count:1
        }
    },
    et:{
        name:"电磁涡轮",
        level:4,
        make:{
            item:[{
                id:"em",
                count:2
            },{
                id:"coil",
                count:2
            }],
            time:2,
            count:2
        }
    },
    superRing:{
        name:"超级磁场环",
        level:5,
        make:{
            item:[{
                id:"et",
                count:2
            },{
                id:"magnet",
                count:3,
            },{
                id:"eg",
                count:1,
            }],
            time:3,
            count:1
        }
    },
    roil:{
        name:"精炼油",
        level:2,
        make:{
            item:[{
                id:"oil",
                count:2
            }],
            time:4,
            count:2
        }
    },
    acid:{
        name:"硫酸",
        level:3,
        make:{
            item:[{
                id:"roil",
                count:6
            },{
                id:"CaM",
                count:8
            },{
                id:"water",
                count:4
            }],
            time:6,
            count:4
        }
    },
    ta:{
        name:"钛合金",
        level:4,
        make:{
            item:[{
                id:"steal",
                count:4
            },{
                id:"Ti",
                count:4
            },{
                id:"acid",
                count:8
            }],
            time:12,
            count:4
        }
    },
    tc:{
        name:"加力推进器",
        level:5,
        make:{
            item:[{
                id:"ta",
                count:5,
            },{
                id:"et",
                count:5
            }],
            time:6,
            count:1
        }
    },
    h2:{
        name:"氢",
        level:1,
        make:{
            item:[{
                id:"oil",
                count:2
            }],
            time:4,
            count:1
        }

    },
    oh:{
        name:"重氢",
        level:1,
        make:{
            item:[{
                id:"h2",
                count:10
            }],
            time:5,
            count:5
        }
    },
    cb:{
        name:"电路板",
        level:2,
        make:{
            item:[{
                id:"Cu",
                count:1
            },{
                id:"Fe",
                count:2
            }],
            time:1,
            count:2
        }
    },
    mc:{
        name:"微晶元件",
        level:2,
        make:{
            item:[{
                id:"Si",
                count:2
            },{
                id:"Cu",
                count:1
            }],
            time:2,
            count:1
        }
    },
    processor:{
        name:"处理器",
        level:3,
        make:{
            item:[{
                id:"mc",
                count:2
            },{
                id:"cb",
                count:2
            }],
            time:3,
            count:1
        }
    },
    plastic:{
        name:"塑料",
        level:3,
        make:{
            item:[{
                id:"roil",
                count:2
            },{
                id:"eg",
                count:1
            }],
            time:3,
            count:1
        }
    },
    oc:{
        name:"有机晶体",
        level:3,
        make:{
            item:[{
                id:"plastic",
                count:2
            },{
                id:"roil",
                count:1
            },{
                id:"water",
                count:1
            }],
            time:6,
            count:1
        }
    },
    Tis:{
        name:"钛晶石",
        level:4,
        make:{
            item:[{
                id:"Ti",
                count:3
            },{
                id:"oc",
                count:1
            }],
            time:4,
            count:1
        }
    },
    grap:{
        name:"石墨烯",
        level:2,
        make:{
            item:[{
                id:"eg",
                count:3
            },{
                id:"acid",
                count:1
            }],
            time:3,
            count:2
        }
    },
    spacew:{
        name:"空间翘曲器",
        level:7,
        make:{
            item:[{
                id:"m5",
                count:1
            }],
            time:10,
            count:8
        }
    },
    cc:{
        name:"卡西米尔晶体",
        level:5,
        make:{
            item:[{
                id:"grap",
                count:2
            },{
                id:"h2",
                count:12
            },{
                id:"Tis",
                count:1
            }],
            time:4,
            count:1
        }
    },
    pe:{
        name:"电浆激发器",
        level:3,
        make:{
            item:[{
                id:"prism",
                count:2
            },{
                id:"coil",
                count:4
            }],
            time:2,
            count:1
        }
    },
    tglass:{
        name:"钛玻璃",
        level:3,
        make:{
            item:[{
                id:"Ti",
                count:2
            },{
                id:"water",
                count:2
            },{
                id:"glass",
                count:2
            }],
            time:3,
            count:2
        }
    },
    pfilter:{
        name:"位面过滤器",
        level:6,
        make:{
            item:[{
                id:"tglass",
                count:2
            },{
                id:"cc",
                count:1
            }],
            time:12,
            count:1
        }
    },
    qchip:{
        name:"量子芯片",
        level:8,
        make:{
            item:[{
                id:"pfilter",
                count:2
            },{
                id:"processor",
                count:2
            }],
            time:6,
            count:1
        }
    },
    cpipe:{
        name:"碳纳米管",
        level:2,
        make:{
            item:[{
                id:"grap",
                count:3
            },{
                id:"Ti",
                count:1
            }],
            time:4,
            count:2
        }
    },
    fm:{
        name:"框架材料",
        level:4,
        make:{
            item:[{
                id:"cpipe",
                count:4
            },{
                id:"Si",
                count:1
            },{
                id:"ta",
                count:1
            }],
            time:6,
            count:1
        }
    },
    prism:{
        name:"棱镜",
        level:3,
        make:{
            item:[{
                id:"glass",
                count:3
            }],
            time:2,
            count:2
        }
    },
    phc:{
        name:"光子合并器",
        level:4,
        make:{
            item:[{
                id:"cb",
                count:1
            },{
                id:"prism",
                count:2
            }],
            time:3,
            count:1
        }
    },
    solars:{
        name:"太阳帆",
        level:5,
        make:{
            item:[{
                id:"phc",
                count:1
            },{
                id:"grap",
                count:1
            }],
            time:4,
            count:2
        }
    },
    dsc:{
        name:"戴森球组件",
        level:6,
        make:{
            item:[{
                id:"solars",
                count:3
            },{
                id:"fm",
                count:3
            },{
                id:"processor",
                count:3
            }],
            time:8,
            count:1
        }
    },
    rocket:{
        name:"小型运载火箭",
        level:8,
        make:{
            item:[{
                id:"drod",
                count:2
            },{
                id:"qchip",
                count:2
            },{
                id:"dsc",
                count:2
            }],
            time:6,
            count:1
        }
    },
    diamond:{
        name:"金刚石",
        level:3,
        make:{
            item:[{
                id:"eg",
                count:1
            }],
            time:2,
            count:1
        }
    },
    cs:{
        name:"晶格硅",
        level:2,
        make:{
            item:[{
                id:"Si",
                count:1
            }],
            time:2,
            count:1
        }
    },
    pb:{
        name:"粒子带宽",
        level:3,
        make:{
            item:[{
                id:"cpipe",
                count:2
            },{
                id:"plastic",
                count:1
            },{
                id:"cs",
                count:2
            }],
            time:8,
            count:1
        }
    },
    pc:{
        name:"粒子容器",
        level:5,
        make:{
            item:[{
                id:"et",
                count:2
            },{
                id:"Cu",
                count:2
            },{
                id:"grap",
                count:2
            }],
            time:4,
            count:1
        }
    },
    tc:{
        name:"推进器",
        level:3,
        make:{
            item:[{
                id:"steal",
                count:2
            },{
                id:"Cu",
                count:3
            }],
            time:4,
            count:1
        }
    },
    ld:{
        name:"物流运输机",
        level:4,
        make:{
            item:[{
                id:"Fe",
                count:5
            },{
                id:"processor",
                count:2
            },{
                id:"tc",
                count:2
            }],
            time:4,
            count:1
        }
    },
    sm:{
        name:"奇异物质",
        level:6,
        make:{
            item:[{
                id:"pc",
                count:2
            },{
                id:"Fe",
                count:2
            },{
                id:"oh",
                count:10
            }],
            time:8,
            count:1
        }
    },
    gl:{
        name:"引力透镜",
        level:7,
        make:{
            item:[{
                id:"diamond",
                count:4
            },{
                id:"sm",
                count:1
            }],
            time:6,
            count:1
        }
    },
    photon:{
        name:"光子",
        level:0
    },
    antimatter:{
        name:"反物质",
        level:2,
        make:{
            item:[{
                id:"photon",
                count:2
            }],
            time:2,
            count:2
        }
    },
    arod:{
        name:"反物质燃料棒",
        level:6,
        make:{
            item:[{
                id:"antimatter",
                count:10
            },{
                id:"h2",
                count:10
            },{
                id:"ta",
                count:1
            },{
                id:"acs",
                count:1
            }],
            time:20,
            count:1
        }
    },
    drod:{
        name:"氘核燃料罐",
        level:5,
        make:{
            item:[{
                id:"oh",
                count:10
            },{
                id:"ta",
                count:1
            },{
                id:"superRing",
                count:1
            }],
            time:6,
            count:1
        }
    },
    hrod:{
        name:"液氢燃料棒",
        level:4,
        make:{
            item:[{
                id:"h2",
                count:5
            },{
                id:"Ti",
                count:1
            }],
            time:3,
            count:1
        }
    },
    acs:{
        name:"湮灭约束球",
        level:5,
        make:{
            item:[{
                id:"pc",
                count:1
            },{
                id:"processor",
                count:1
            }],
            time:20,
            count:1
        }
    },
    m1:{
        name:"电磁矩阵",
        level:3,
        make:{
            item:[{
                id:"coil",
                count:1
            },{
                id:"cb",
                count:1
            }],
            time:3,
            count:1
        }
    },
    m2:{
        name:"能量矩阵",
        level:3,
        make:{
            item:[{
                id:"eg",
                count:2
            },{
                id:"h2",
                count:2
            }],
            time:6,
            count:1
        }
    },
    m3:{
        name:"结构矩阵",
        level:3,
        make:{
            item:[{
                id:"diamond",
                count:1
            },{
                id:"Tis",
                count:1
            }],
            time:8,
            count:1
        }
    },
    m4:{
        name:"信息矩阵",
        level:4,
        make:{
            item:[{
                id:"processor",
                count:2
            },{
                id:"pb",
                count:1
            }],
            time:10,
            count:1
        }
    },
    m5:{
        name:"引力矩阵",
        level:8,
        make:{
            item:[{
                id:"qchip",
                count:1
            },{
                id:"gl",
                count:1
            }],
            time:24,
            count:2
        }
    },
    m6:{
        name:"宇宙矩阵",
        level:9,
        make:{
            item:[{
                id:"m1",
                count:1
            },{
                id:"m2",
                count:1
            },{
                id:"m3",
                count:1
            },{
                id:"m4",
                count:1
            },{
                id:"m5",
                count:1
            },{
                id:"antimatter",
                count:1
            }],
            time:15,
            count:1
        }
    }    
}

var replaceData={
    ccStone:{
        re:{
            id:"phc",
            make:{
                item:[{
                    id:"ccStone",
                    count:1
                },{
                    id:"cb",
                    count:1
                }],
                time:3,
                count:1
            }
        },
        re1:{
            id:"cc",
            make:{
                item:[{
                    id:"ccStone",
                    count:6
                },{
                    id:"grap",
                    count:2
                },{
                    id:"h2",
                    count:12
                }],
                time:4,
                count:1
            }
        }
    },
    csStone:{
        re:{
            id:"cs",
            make:{
                item:[{
                    id:"csStone",
                    count:1
                }],
                time:4,
                count:1
            }
        }
    },
    dStone:{
        re:{
            id:"diamond",
            make:{
                item:[{
                    id:"dStone",
                    count:1
                }],
                time:2,
                count:1
            }
        }
    },
    cice:{
        re:{
            id:"grap",
            make:{
                item:[{
                    id:"cice",
                    count:2
                }],
                time:2,
                count:2
            }
        }
    },
    cStone:{
        re:{
            id:"cpipe",
            make:{
                item:[{
                    id:"cStone",
                    count:2
                }],
                time:2,
                count:2
            }
        }
    },
    pcStone:{
        re:{
            id:"pc",
            make:{
                item:[{
                    id:"pcStone",
                    count:10
                },{
                    id:"Cu",
                    count:2
                }],
                time:4,
                count:1
            }
            
        }
    }
}